  spring:
     profiles:
        active:
        - dev
  - - -
  spring:
      profiles: dev
      application:
          name: servicecloud-config-atguigu-dev
  - - -
  spring:
      profiles: test
      application:
          name: servicecloud-config-atguigu-test